title: "New Hypos Taejong Blog"
description: "Windows Application and Web Application Development Blog"
theme: minima
# If you use a custom domain, add it via the GitHub UI and create a CNAME file at the repo root.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/yourname

header_pages:
  - pages/utilities.md          # 유틸리티 모음
  - docs/install-update.md      # 설치 및 업데이트 안내
  - docs/faq.md                 # FAQ
